### ISSUE TITLE
Can not verify balance when following the tutorial

### ISSUE THREAD

**Issue by vgrabovski-lacero-platform** [0xPolygonID/onchain-merklized-issuer-demo#4]
Hello, I was trying to follow this [tutorial](https://devs.polygonid.com/docs/issuer/on-chain-issuer/on-chain-tutorial/) to issue balance credentials and verify them. The issuance was successful, so the credentials were added to my polygon.id wallet.

However, when I tried to [verify it](https://devs.polygonid.com/docs/issuer/on-chain-issuer/on-chain-tutorial/#how-to-verify-the-balance-claim), an error popped up with the following description: **CredentialsNotFoundException**.

Please check the attached screenshots. Hope this could help to localize a problem.
___

**Credentials issuance:**

Step a
<img width="1192" alt="Screenshot 2024-05-28 at 11 42 05" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/5fe208ca-f368-416f-8b23-0b37eadff58c">

Step b
<img width="904" alt="Screenshot 2024-05-28 at 11 42 17" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/52968788-7f0e-402b-a234-01fd7659a9a9">

Step c
<img width="401" alt="Screenshot 2024-05-28 at 11 42 23" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/95510884-7461-4ddc-8138-5aae45e579bb">

Step d
<img width="555" alt="Screenshot 2024-05-28 at 11 42 31" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/d2568180-5d0f-412d-9750-954805a8b741">

Step e
<img width="1056" alt="Screenshot 2024-05-28 at 11 44 58" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/b0901e19-8c77-4948-817c-9e05c4c71d49">
___

**Polygon.id wallet with issued credentials:**

![photo_2024-05-28_12-02-29](https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/fff9c7fb-64cc-42cf-84fd-5657ec248470)
___

**Verification using [query builder](https://schema-builder.polygonid.me/query-builder):**

Step a
<img width="943" alt="Screenshot 2024-05-28 at 12 12 33" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/f50e2c6a-382e-4bd8-bab2-a2e86741f5bd">

Step b
<img width="965" alt="Screenshot 2024-05-28 at 11 46 52" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/4cc98bbd-c011-4266-8497-76d6a3b1867e">

Step c
<img width="740" alt="Screenshot 2024-05-28 at 11 46 59" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/0aa1c1a0-f653-49ea-814e-3094e1732ee3">
___

**Polyon.id wallet proof error:**

![photo_2024-05-28_12-02-33](https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/d68b1f8a-901d-4f7b-a9a6-6ca3f71139ee)

**Comment by ilya-korotya** [comment]
Hi @vgrabovski-lacero-platform. Thank you for creating this question. Could you try to use this json-ld context: ipfs://QmbbTKPTJy5zpS2aWBRps1duU8V3zC84jthpWDXE9mLHBX in query builder to verify the balance credential?

**Comment by vgrabovski-lacero-platform** [comment]
And now it works as required. Thanks @ilya-korotya 


<img width="978" alt="Screenshot 2024-05-28 at 13 38 23" src="https://github.com/0xPolygonID/onchain-merklized-issuer-demo/assets/72795514/8f2c3216-f53a-4805-a7bb-cc1eff0755cb">


Docs seem to be obsolete a bit, as I might assume.
